name: Benchmarks

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup lde
        uses: lde-org/setup-lde@master
        with:
          version: nightly

      - name: Install benchmark environment
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks lua5.1 liblua5.1-0-dev pkg-config

          # Lux needs this apparently
          sudo ln -sf /usr/bin/lua5.1 /usr/local/bin/lua

      - name: Install hyperfine
        run: |
          curl -fsSL https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-v1.20.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv hyperfine-v1.20.0-x86_64-unknown-linux-gnu/hyperfine /usr/local/bin/hyperfine

      - name: Install lux
        run: |
          curl -fsSL https://github.com/lumen-oss/lux/releases/download/v0.40.1/lx-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv lx /usr/local/bin/lx

      - name: Run benchmarks
        run: |
          cd benchmarks
          lde run
