name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            outfile: lpm-linux-x86-64
          - os: ubuntu-22.04-arm
            outfile: lpm-linux-aarch64
          - os: windows-latest
            outfile: lpm-windows-x86-64.exe
          - os: windows-11-arm
            outfile: lpm-windows-aarch64.exe
          # - os: macos-15-intel
          #   outfile: lpm-macos-x86-64
          - os: macos-15
            outfile: lpm-macos-aarch64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup lpm
        uses: codebycruz/lpm@master
        with:
          version: nightly

      - name: Build lpm
        run: |
          cd packages/lpm
          lpm compile --outfile ${{ matrix.outfile }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: packages/lpm/${{ matrix.outfile }}
